# Generated by Django 4.2.2 on 2023-07-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationid', models.IntegerField(max_length=255)),
                ('addressline1', models.CharField(max_length=255)),
                ('addressline2', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('contactnumber', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
