# Generated by Django 4.2.2 on 2023-07-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_home3'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOTIFICATION', models.CharField(max_length=255)),
                ('CURRENTDATE', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='contactnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home1',
            name='aadharnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home1',
            name='contactnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home1',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home2',
            name='contactnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home2',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home2',
            name='stationid',
            field=models.CharField(max_length=255),
        ),
    ]
