# Generated by Django 4.2.2 on 2023-07-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_noti_alter_home_contactnumber_alter_home_pincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCHOME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCHEME_TYPE', models.CharField(max_length=255)),
                ('SCHEME_NAME', models.CharField(max_length=255)),
                ('SCHEME_AMOUNT', models.IntegerField(null=True)),
                ('MONTHLY_AMOUNT', models.IntegerField(null=True)),
                ('INTEREST_RATE', models.CharField(max_length=255)),
                ('SCHEME_DETAILS', models.CharField(max_length=255)),
            ],
        ),
    ]
