# Generated by Django 4.2.2 on 2023-07-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_schome'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPLAINT_SUBJECT', models.CharField(max_length=255)),
                ('COMPLAINT', models.CharField(max_length=255)),
            ],
        ),
    ]
