# Generated by Django 4.2.2 on 2023-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='COMPLAINT',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='home1',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='home2',
            name='addressline1',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='home2',
            name='addressline2',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='noti',
            name='NOTIFICATION',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schome',
            name='SCHEME_DETAILS',
            field=models.TextField(max_length=255),
        ),
    ]
