# Generated by Django 4.2.2 on 2023-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_comp_complaint_alter_home_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATTENDANCE', models.CharField(choices=[('P', 'PRESENT'), ('A', 'ABSENT')], max_length=25)),
            ],
        ),
    ]
