# Generated by Django 4.2.2 on 2023-07-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_home7'),
    ]

    operations = [
        migrations.AddField(
            model_name='home7',
            name='WORKER_ID',
            field=models.IntegerField(null=True),
        ),
    ]
