# Generated by Django 4.2.2 on 2023-07-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_home7_worker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JOB_CATEGORY', models.CharField(choices=[('PAINTING', 'PAINTING'), ('CONSTRUCTION', 'CONSTRUCTION'), ('PLUMBER', 'PLUMBER'), ('ELECTRICIAN', 'ELECTRICIAN'), ('MECHANIC', 'MECHANIC'), ('LIFT OPERATOR', 'LIFT OPERATOR')], max_length=25)),
                ('SALARY_PER_DAY', models.IntegerField(null=True)),
            ],
        ),
    ]
