# Generated by Django 4.2.2 on 2023-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_home8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JOB_CATEGORY', models.CharField(choices=[('PAINTING', 'PAINTING'), ('CONSTRUCTION', 'CONSTRUCTION'), ('PLUMBER', 'PLUMBER'), ('ELECTRICIAN', 'ELECTRICIAN'), ('MECHANIC', 'MECHANIC'), ('LIFT OPERATOR', 'LIFT OPERATOR')], max_length=25)),
                ('WORKER_ID', models.IntegerField(null=True)),
                ('WORKER_NAME', models.CharField(max_length=255)),
            ],
        ),
    ]
