# Generated by Django 4.2.2 on 2023-07-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_home9'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home9',
            old_name='WORKER_NAME',
            new_name='workername',
        ),
    ]
