# Generated by Django 4.2.2 on 2023-07-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_worker_name_home9_workername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home9',
            name='workername',
            field=models.CharField(max_length=210),
        ),
    ]
