# Generated by Django 4.2.2 on 2023-07-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_home9_workername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home9',
            name='WORKER_ID',
        ),
        migrations.RemoveField(
            model_name='home9',
            name='workername',
        ),
        migrations.AddField(
            model_name='home9',
            name='WORKER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home1'),
        ),
        migrations.AlterField(
            model_name='home7',
            name='WORKER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home1'),
        ),
    ]
