# Generated by Django 4.2.2 on 2023-07-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_home9_worker_id_remove_home9_workername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home7',
            old_name='WORKER_ID',
            new_name='WORKER',
        ),
    ]
