# Generated by Django 4.2.2 on 2023-07-29 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_worker_id_home7_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CURRENTDATE', models.DateField(null=True)),
                ('Worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home1')),
            ],
        ),
    ]
