# Generated by Django 4.2.2 on 2023-07-31 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_home_user_type_home1_user_type_home2_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CURRENTDATE', models.DateField(null=True)),
                ('Scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.schome')),
                ('Worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home1')),
            ],
        ),
    ]
