# Generated by Django 4.2.2 on 2023-08-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_home11'),
    ]

    operations = [
        migrations.AddField(
            model_name='home1',
            name='pass_status',
            field=models.IntegerField(null=True),
        ),
    ]
