# Generated by Django 4.2.2 on 2023-08-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_home12'),
    ]

    operations = [
        migrations.AddField(
            model_name='home1',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home'),
        ),
    ]
