# Generated by Django 4.2.2 on 2023-08-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_home13_applyscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home13',
            name='file',
            field=models.FileField(upload_to='newuploads/'),
        ),
    ]
