# Generated by Django 4.2.2 on 2023-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_home13_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='home13',
            name='payment_status',
            field=models.IntegerField(null=True),
        ),
    ]
