# Generated by Django 4.2.2 on 2023-08-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_home13_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameoncard', models.CharField(max_length=255)),
                ('Cardnumber', models.IntegerField(null=True)),
                ('CVV', models.IntegerField(null=True)),
                ('Expiredate', models.CharField(max_length=255)),
                ('Amount', models.IntegerField(null=True)),
                ('Date', models.DateField(null=True)),
                ('Claimscheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.schome')),
                ('Insuranceagency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home3')),
            ],
        ),
    ]
