# Generated by Django 4.2.2 on 2023-08-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_home14'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='admin123@gmail.com', max_length=255)),
                ('password', models.CharField(default='admin123', max_length=255)),
            ],
        ),
    ]
