# Generated by Django 4.2.2 on 2023-08-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_home15'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='labourcommission123@gmail.com', max_length=255)),
                ('password', models.CharField(default='labourcommission123', max_length=255)),
            ],
        ),
    ]
