# Generated by Django 4.2.2 on 2023-09-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_home17'),
    ]

    operations = [
        migrations.AddField(
            model_name='home7',
            name='currentmonth',
            field=models.DateField(null=True),
        ),
    ]
