# Generated by Django 4.2.2 on 2023-09-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_home7_currentmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home7',
            name='currentmonth',
            field=models.IntegerField(null=True),
        ),
    ]
