# Generated by Django 4.2.2 on 2023-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_home7_currentmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='home9',
            name='Working_place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
