# Generated by Django 4.2.2 on 2023-09-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_home2_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='home1',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
