# Generated by Django 4.2.2 on 2023-09-14 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_home1_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home1',
            name='file',
        ),
        migrations.CreateModel(
            name='Home18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('Worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home1')),
            ],
        ),
    ]
